import { useEffect, useState } from "react";
import { AnimatePresence, motion } from "motion/react";
import { ArrowUpRight, Award, BriefcaseBusiness, Github, Home, Mail, Moon, PanelsTopLeft, Sun, X } from "lucide-react";
import { copy, experiences, projects, type Language, type Localized, type Project } from "./data/content";
import { AmbientBackground } from "./components/AmbientBackground";
import { IntroScreen } from "./components/IntroScreen";
import { LanguageSelector } from "./components/LanguageSelector";
import { CertificationsSection } from "./components/CertificationsSection";
import "./styles.css";

export default function App() {
  const [showIntro,setShowIntro]=useState(true);
  const [dark,setDark]=useState(()=>localStorage.getItem("theme")==="dark");
  const [language,setLanguage]=useState<Language>(()=>localStorage.getItem("language")==="es"?"es":"en");
  const [selectedProject,setSelectedProject]=useState<Project|null>(null);
  const [experienceOpen,setExperienceOpen]=useState(false);
  const t=copy[language]; const tx=(value:Localized)=>value[language];

  useEffect(()=>{const timer=window.setTimeout(()=>setShowIntro(false),1450);return()=>window.clearTimeout(timer)},[]);
  useEffect(()=>{document.documentElement.dataset.theme=dark?"dark":"light";localStorage.setItem("theme",dark?"dark":"light")},[dark]);
  useEffect(()=>{document.documentElement.lang=language;localStorage.setItem("language",language)},[language]);
  useEffect(()=>{if(!selectedProject&&!experienceOpen)return;const close=(e:KeyboardEvent)=>{if(e.key==="Escape"){setSelectedProject(null);setExperienceOpen(false)}};document.body.classList.add("modal-open");window.addEventListener("keydown",close);return()=>{document.body.classList.remove("modal-open");window.removeEventListener("keydown",close)}},[selectedProject,experienceOpen]);

  const capabilities=language==="en"?["Applied AI","AI agents","Business development","Customer discovery","CRM workflows","Pipeline management","Business analysis","Process improvement","FastAPI","PostgreSQL","Supabase","React"]:["IA aplicada","Agentes de IA","Desarrollo de negocios","Descubrimiento de clientes","Flujos de CRM","Gestión de pipeline","Análisis de negocio","Mejora de procesos","FastAPI","PostgreSQL","Supabase","React"];

  return <><AmbientBackground/><IntroScreen visible={showIntro}/><LanguageSelector language={language} onChange={setLanguage}/><main className="shell">
    <header className="hero" id="home"><div className="availability"><span/>{t.available}</div><motion.h1 initial={{opacity:0,y:18}} animate={{opacity:1,y:0}}>Emiliano<br/>González Romo</motion.h1><p className="lede">{t.hero}</p><div className="actions"><a className="button primary" href="#work">{t.view}<ArrowUpRight size={16}/></a><a className="button" href="https://github.com/h8hyf2rw9y-afk" target="_blank" rel="noopener noreferrer">{t.github}<Github size={16}/></a></div></header>
    <section id="about"><p className="kicker">{t.about}</p><h2>{t.aboutTitle}</h2><p className="body-copy">{t.aboutBody}</p></section>
    <section id="experience"><p className="kicker">{t.experience}</p><h2>{t.value}</h2><motion.button type="button" className="experience-card experience-card-complete" onClick={()=>setExperienceOpen(true)} initial={{opacity:0,y:18}} whileInView={{opacity:1,y:0}} viewport={{once:true}}><div className="experience-card-header"><span>{language==="en"?"Complete experience":"Experiencia completa"}</span><strong>02</strong></div><div><h3>{language==="en"?"Real estate, technology, and business":"Bienes raíces, tecnología y negocio"}</h3><p>{language==="en"?"Explore my experience across client work, operations, product thinking, and technology projects in one complete view.":"Explora mi experiencia en trabajo con clientes, operaciones, pensamiento de producto y proyectos tecnológicos en una sola vista."}</p><div className="experience-preview-list">{experiences.map(item=><span key={`${item.company}-${item.role.en}`}>{item.company} · {tx(item.role)}</span>)}</div><span className="view-project">{language==="en"?"View complete experience":"Ver experiencia completa"}<ArrowUpRight size={15}/></span></div></motion.button></section>
    <section id="work"><p className="kicker">{t.work}</p><h2>{t.workTitle}</h2><div className="project-grid">{projects.map((project,index)=><motion.button type="button" className={`project-card ${project.tone}`} key={project.title} initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:(index%4)*.06}} onClick={()=>setSelectedProject(project)}><span className="tag">{tx(project.label)}</span><div><h3>{project.title}</h3><p>{tx(project.description)}</p><p className="inspiration-preview"><span>{t.inspired}</span>{tx(project.inspiration)}</p><small>{project.stack}</small><span className="view-project">{t.explore}<ArrowUpRight size={15}/></span></div></motion.button>)}</div></section>
    <section id="skills"><p className="kicker">{t.skills}</p><h2>{t.skillsTitle}</h2><div className="pills">{capabilities.map(item=><span key={item}>{item}</span>)}</div></section>
    <CertificationsSection language={language} />
    <section id="education"><p className="kicker">{t.education}</p><h2>{t.educationTitle}</h2><div className="timeline"><article><time>{t.graduated}</time><div><h3>{t.degree}</h3><p>Tecnológico de Monterrey · Campus Monterrey</p></div></article><article><time>{t.learning}</time><div><h3>{t.programs}</h3><p>McKinsey Forward · AWS Cloud Foundations · Dell Setting Up Your Sale · Introduction to Generative AI · Jira · CAPM preparation</p></div></article></div></section>
    <section className="contact" id="contact"><p className="kicker">{t.contact}</p><h2>{t.contactTitle}</h2><p className="body-copy">{t.contactBody}</p><div className="contact-card"><div><span>{t.privateContact}</span><strong>em••••••@gmail.com</strong><p>{t.privateBody}</p></div><button disabled>{t.coming}<Mail size={16}/></button></div></section>
    <footer>© 2026 Emiliano González Romo · {t.copyright}</footer>
  </main>
  <AnimatePresence>{experienceOpen&&<motion.div className="project-overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setExperienceOpen(false)}} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><motion.section className="project-modal experience-modal experience-modal-complete" role="dialog" aria-modal="true" aria-labelledby="experience-title" initial={{opacity:0,y:36,scale:.96}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:24,scale:.97}} transition={{type:"spring",stiffness:280,damping:28}}><button className="modal-close" onClick={()=>setExperienceOpen(false)} aria-label={t.close}><X/></button><span className="tag">{language==="en"?"Complete experience":"Experiencia completa"}</span><h2 id="experience-title">{language==="en"?"Professional journey":"Trayectoria profesional"}</h2><p className="modal-intro">{language==="en"?"A complete view of how I connect client work, business operations, product thinking, and technology.":"Una vista completa de cómo conecto el trabajo con clientes, operaciones, pensamiento de producto y tecnología."}</p><div className="experience-detail-list">{experiences.map(experience=><article key={experience.role.en}><div className="experience-detail-heading"><time>{tx(experience.period)}</time><div><span className="experience-company">{experience.company}</span><h3>{tx(experience.role)}</h3><p className="experience-meta">{tx(experience.meta)}</p></div></div><p>{tx(experience.overview)}</p><div className="detail-block"><span>{language==="en"?"Core responsibilities":"Responsabilidades principales"}</span><ul>{experience.responsibilities[language].map(item=><li key={item}>{item}</li>)}</ul></div><small>{experience.tools}</small></article>)}</div></motion.section></motion.div>}</AnimatePresence>
  <AnimatePresence>{selectedProject&&<motion.div className="project-overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setSelectedProject(null)}} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><motion.section className="project-modal" role="dialog" aria-modal="true" aria-labelledby="project-title" initial={{opacity:0,y:36,scale:.96}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:24,scale:.97}} transition={{type:"spring",stiffness:280,damping:28}}><button className="modal-close" onClick={()=>setSelectedProject(null)} aria-label={t.close}><X/></button><span className="tag">{tx(selectedProject.label)}</span><h2 id="project-title">{selectedProject.title}</h2><p className="modal-intro">{tx(selectedProject.description)}</p><div className="detail-block inspiration-detail"><span>{t.inspired}</span><p>{tx(selectedProject.inspiration)}</p></div><div className="detail-grid"><div><span>{t.problem}</span><p>{tx(selectedProject.problem)}</p></div><div><span>{t.solution}</span><p>{tx(selectedProject.solution)}</p></div></div><div className="detail-block"><span>{t.contribution}</span><p>{tx(selectedProject.contribution)}</p></div><div className="detail-block"><span>{t.capabilities}</span><ul>{selectedProject.highlights[language].map(item=><li key={item}>{item}</li>)}</ul></div><div className="modal-footer"><div><span>{t.status}</span><strong>{tx(selectedProject.status)}</strong></div><small>{selectedProject.stack}</small></div></motion.section></motion.div>}</AnimatePresence>
  <nav className="dock" aria-label="Portfolio navigation"><a href="#home" aria-label="Home"><Home/></a><a href="#work" aria-label="Projects"><PanelsTopLeft/></a><a href="#experience" aria-label="Experience"><BriefcaseBusiness/></a><a href="#certifications" aria-label="Certifications"><Award/></a><a href="#contact" aria-label="Contact"><Mail/></a><button onClick={()=>setDark(v=>!v)} aria-label="Toggle color theme">{dark?<Sun/>:<Moon/>}</button></nav>
  </>;
}
